name: "[collab-vm-server] make"

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  check_skip:
    runs-on: ubuntu-18.04
    outputs:
      skip: ${{ steps.result_step.outputs.result }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: mstachniuk/ci-skip@master
        with:
          commit-filter: '[skip ci];[ci skip]'
          commit-filter-separator: ';'
      - run: echo "::set-output name=result::${CI_SKIP}"
        id: result_step

  build_png:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install depends
      run: |
        sudo apt-get update
        ./scripts/grab_deps_linux.sh 
    - name: Make PNG build
      run: |
        mkdir obj
        odb -d sqlite -o obj -s -q src/Database/Config.h -v -x -mtune=generic
        odb -d sqlite -o obj -s -q src/Database/VMSettings.h -v -x -mtune=generic
  build_jpeg:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install depends
      run: |
        sudo apt-get update
        ./scripts/grab_deps_linux.sh 
    - name: Make JPEG build
      run: |
        mkdir obj
        odb -d sqlite -o obj -s -q src/Database/Config.h -v
        odb -d sqlite -o obj -s -q src/Database/VMSettings.h -v
