name: "[collab-vm-server] make"

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.result_step.outputs.result }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: mstachniuk/ci-skip@master
        with:
          commit-filter: '[skip ci];[ci skip]'
          commit-filter-separator: ';'
      - run: echo "::set-output name=result::${CI_SKIP}"
        id: result_step

  build_png:
    needs: check_skip
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
    - run: sudo apt-get update
    - run: sudo apt-get install -y odb
    - run: ./scripts/grab_deps_linux.sh 
    - name: make
    - run: make
    - name: Upload Artifact - PNG
      uses: 'actions/upload-artifact@v2'
      with:
        name: Server Binary - PNG
        path: './bin/**/*'
  build_jpeg:
    needs: check_skip
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
    - run: sudo apt-get update
    - run: sudo apt-get install -y odb
    - run: ./scripts/grab_deps_linux.sh 
    - name: make-jpeg
    - run: make JPEG=1
    - name: Upload Artifact - JPEG
      uses: 'actions/upload-artifact@v2'
      with:
        name: Server Binary - JPEG
        path: './bin/**/*'
     
